# Generated by Django 4.1.3 on 2024-08-14 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bronzemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='bronzemodel',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user.userprofile'),
        ),
    ]
