# Generated by Django 4.1.3 on 2024-08-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile'),
        ('subscriptions', '0002_remove_bronzemodel_user_bronzemodel_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bronzemodel',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user.userprofile'),
        ),
    ]
