# Generated by Django 4.1.3 on 2024-09-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_bronzemodel_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BronzeModel',
        ),
    ]
