# Generated by Django 4.1.3 on 2024-09-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_taskmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='task_count',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tasks_completed',
            field=models.IntegerField(default=0),
        ),
    ]
