# Generated by Django 5.1.1 on 2024-09-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_taskmodel_task_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.BooleanField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='category',
            field=models.CharField(choices=[('sport', 'Sport'), ('work', 'Work'), ('study', 'Study'), ('leisure', 'Leisure'), ('other', 'Other')], default=(('sport', 'Sport'),), max_length=30),
            preserve_default=False,
        ),
    ]
