# Generated by Django 5.1.1 on 2024-10-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_taskmodel_updated_at_alter_taskmodel_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='execution_time',
            field=models.FloatField(default=0.0),
        ),
    ]
