# Generated by Django 5.1.1 on 2024-10-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_taskmodel_execution_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='execution_time',
        ),
    ]
